import { defineStore } from 'pinia';

export const useProjectStoreDev = defineStore('projectStore', {
	state: () => ({
		projects: [
			{
				id: 1,
				imgpre: '/dev/tracker11.jpg',
				image: '/dev/tracker1.jpg',
				images: [
					{ type: 'image', src: '/dev/tracker1.jpg' },
					{ type: 'image', src: '/dev/tracker2.jpg' },
					{ type: 'image', src: '/dev/tracker3.jpg' },
					{ type: 'image', src: '/dev/tracker4.jpg' },
				],
				title: 'Games Tracker',
				subtitle: 'Codice per divertimento',
				paragraph1: 'Applicazione web per gestire e analizzare la propria libreria videoludica.',
				paragraph2: `L'architettura garantisce l'aggiornamento in tempo reale dei dati grazie alle API di Steam.`,
				tags: ['Vite', 'React', 'Tailwind', 'Typescript', 'Steam API'],
				classCust: 'scale-140 object-contain',
			},
			{
				id: 2,
				image: '/dev/Boolzapp2.png',
				imgpre: '/dev/Boolzapp2.jpg',
				images: [{ type: 'image', src: '/dev/Boolzapp2.png' }],
				title: 'Boolzapp',
				subtitle: 'Boolean',
				paragraph1: 'Il progetto prevedeva di realizzare una replica della web-app di Whatsapp.',
				paragraph2: `Funzionalità chiave: ordinamento cronologico delle chat, ricerca avanzata e risposte automatiche.`,
				tags: ['HTML', `CSS`, `JavaScript`, 'Bootstrap'],
				classCust: 'scale-175 object-contain',
			},
			{
				id: 3,
				imgpre: '/dev/Boolflix.jpg',
				title: 'Boolflix',
				image: '/dev/boolflix1r.jpg',
				images: [
					{ type: 'image', src: '/dev/boolflix1r.jpg' },
					{ type: 'image', src: '/dev/boolflix2r.jpg' },
					{ type: 'image', src: '/dev/boolflix3r.jpg' },
				],
				subtitle: 'Boolean',
				paragraph1: 'Il progetto prevedeva di realizzare una replica della web-app di Netflix.',
				paragraph2: `Nella home sono presenti le liste dei Film e SerieTv più popolari. Nella SearchBar è possibile cercare Film e SerieTv. Cliccando sull'opera desiderata, si aprirà una modale.`,
				tags: ['Vite', 'Vue', 'JavaScript'],
				classCust: 'object-contain',
			},
			{
				id: 4,
				image: '/dev/docVue.png',
				imgpre: '/dev/docVue.jpg',
				images: [
					{ type: 'image', src: '/dev/docVue.png' },
					{ type: 'image', src: '/dev/bdocvue1.jpg' },
					{ type: 'image', src: '/dev/bdocvue2.jpg' },
				],
				title: 'BDoctors (FE)',
				subtitle: 'Boolean',
				paragraph1: 'Il progetto prevedeva di realizzare un sito web gestionale per strutture mediche private.',
				paragraph2:
					'In home sono presenti i medici, prima quelli sponsorizzati e dopo quelli non sponsorizzati. è possibile filtrare i medici per specializzazione',
				tags: ['Vite', 'Vue', 'CSS', `Bootstrap`],
				classCust: 'scale-200',
			},
			{
				id: 5,
				image: '/dev/docLaravel.png',
				imgpre: '/dev/docLaravel.jpg',
				images: [
					{ type: 'image', src: '/dev/docLaravel.png' },
					{ type: 'image', src: '/dev/bDoc/bDoctor (1).jpg' },
					{ type: 'image', src: '/dev/bDoc/bDoctor (2).jpg' },
					{ type: 'image', src: '/dev/bDoc/bDoctor (3).jpg' },
					{ type: 'image', src: '/dev/bDoc/bDoctor (4).jpg' },
					{ type: 'image', src: '/dev/bDoc/bDoctor (5).jpg' },
					{ type: 'image', src: '/dev/bDoc/bDoctor (6).jpg' },
					{ type: 'image', src: '/dev/bDoc/bDoctor (7).jpg' },
					{ type: 'image', src: '/dev/bDoc/bDoctor (8).jpg' },
					{ type: 'image', src: '/dev/bDoc/bDoctor (9).jpg' },
					{ type: 'image', src: '/dev/bDoc/bDoctor (10).jpg' },
					{ type: 'image', src: '/dev/bDoc/bDoctor (11).jpg' },
				],
				title: 'BDoctors (BE)',
				subtitle: 'Boolean',
				paragraph1: `Il sistema richiede l'autenticazione del medico.`,
				paragraph2: `Ciascun medico può accedere a un'area personale dove controllare i messaggi e le recensioni, oppure può anche scegliere di pagare una sponsorizzazione.`,
				tags: ['Vite', `Laravel`, `MySQL`, `Bootstrap`],
				classCust: 'scale-200',
			},
			{
				id: 6,
				imgpre: '/graphic/Guida_Lol.jpg',
				image: '/dev/Guida_LolJ.jpg',
				images: [
					{ type: 'image', src: '/dev/Guida_LolJ.jpg' },
					{ type: 'image', src: '/dev/ezlol/ezLol1.jpg' },
					{ type: 'image', src: '/dev/ezlol/ezLol2.jpg' },
					{ type: 'image', src: '/dev/ezlol/ezLol3.jpg' },
					{ type: 'image', src: '/dev/ezlol/ezLol4.jpg' },
					{ type: 'image', src: '/dev/ezlol/ezLol5.jpg' },
					{ type: 'image', src: '/dev/ezlol/ezLol6.jpg' },
					{ type: 'image', src: '/dev/ezlol/ezLol7.jpg' },
					{ type: 'image', src: '/dev/ezlol/ezLol8.jpg' },
					{ type: 'image', src: '/dev/ezlol/ezLol9.jpg' },
				],
				title: 'Ez+ LoL',
				subtitle: 'Web Design',
				paragraph1: 'Progettazione e sviluppo end-to-end di un sito web.',
				paragraph2:
					"Realizzato completamente in autonomia: dall'UI/UX design all'implementazione con HTML5, CSS3 e JavaScript vanilla, garantendo prestazioni ottimali senza l'utilizzo di framework.",
				tags: ['HTML5', 'CSS3', 'JavaScript', `jQuery`],
				classCust: 'object-cover',
			},
			{
				id: 7,
				imgpre: '/graphic/Guida_Lol_Redone.jpg',
				image: '/dev/ezlol2/ezLol2.jpg',
				images: [
					{ type: 'image', src: '/dev/ezlol2/ezLol2.jpg' },
					{ type: 'image', src: '/dev/ezlol2/ezLol22.jpg' },
					{ type: 'image', src: '/dev/ezlol2/ezLol23.jpg' },
					{ type: 'image', src: '/dev/ezlol2/ezLol24.jpg' },
					{ type: 'image', src: '/dev/ezlol2/ezLol25.jpg' },
					{ type: 'image', src: '/dev/ezlol2/ezLol26.jpg' },
					{ type: 'image', src: '/dev/ezlol2/ezLol27.jpg' },
					{ type: 'image', src: '/dev/ezlol2/ezLol28.jpg' },
					{ type: 'image', src: '/dev/ezlol2/ezLol29.jpg' },
					{ type: 'image', src: '/dev/ezlol2/ezLol210.jpg' },
				],
				title: 'Ez+ LoL',
				subtitle: 'Rifacimento con stack moderno',
				paragraph1: 'Rearchitettura completa del frontend con tecnologie performanti.',
				paragraph2: 'Rewrite completo con stack moderno: Vue 3, Vite e Tailwind per lo styling efficiente.',
				tags: ['Vue 3', 'Vite', 'Tailwind CSS'],
				classCust: 'object-cover',
				classCustCol: 'col-span-12',
				classCustColSec: 'fixGridOn1',
			},
			// Aggiungi altri progetti qui
		],
	}),
	getters: {
		getProjectById: (state) => (id) => {
			return state.projects.find((project) => project.id === id);
		},
	},
});
