import { defineStore } from 'pinia';

export const useProjectStore = defineStore('graphicProjects', {
	state: () => ({
		projects: [
			{
				id: 1,
				imgpre: '/graphic/tesi.jpg',
				image: '/graphic/tesi.png',
				images: ['/graphic/tesi.png', '/graphic/tesi.png', '/graphic/tesi.png'],
				images: [
					{ type: 'image', src: '/graphic/tesi.png' },
					{ type: 'image', src: '/graphic/cover.jpg' },
					{ type: 'image', src: '/graphic/SamCoverGZ.jpg' },
					{ type: 'image', src: '/graphic/SteelBook.png' },
					{ type: 'pdf', src: '/graphic/manuale.pdf' },
				],
				title: 'Ground Zeroes',
				subtitle: 'Tesi',
				paragraph1:
					"Studio approfondito sul processo di sviluppo videoludico, con focus sulle figure professionali coinvolte, l'implementazione di tecnologie innovative (IA incluse).",
				paragraph2:
					'Composta di una dimostrazione pratica attraverso un progetto originale ispirato a Splinter Cell, corredato di mockup digitali.',
				tags: ['Photoshop', 'InDesign', 'Premiere', 'AfterEffects', 'GDevelop', 'Blender'],
				specialClass: 'object-cover object-top',
			},
			{
				id: 2,
				imgpre: '/graphic/magazineEGE.jpg',
				image: '/graphic/magazineEGE.png',
				images: [
					{ type: 'image', src: '/graphic/magazineEGE.png' },
					{ type: 'pdf', src: '/graphic/Portfolio.pdf' },
					{ type: 'pdf', src: '/graphic/O.T.R.pdf' },
				],
				title: 'O.T.R.',
				subtitle: 'Elementi di grafica editoriale',
				paragraph1: "Materia incentrata sull'editoria.",
				paragraph2: 'Il progetto finale prevedeva di realizzare un magazine.',
				tags: ['InDesign', 'Illustrator', `Photoshop`],
				specialClass: 'object-cover object-top',
			},
			{
				id: 3,
				imgpre: '/graphic/infografica.jpg',
				image: '/graphic/infografica.png',
				images: [
					{ type: 'image', src: '/graphic/infografica.png' },
					// { type: 'pdf', src: 'brochure.pdf' },
					// { type: 'image', src: 'img2.jpg' },
				],
				title: 'Infografiche',
				subtitle: 'Graphic Design 3',
				paragraph1: 'Il progetto finale prevedeva di realizzare alcune infografiche',
				paragraph2: 'Tra cui una infografica personale che rappresentasse il mio percorso.',
				tags: ['Photoshop', 'Illustrator', 'InDesign'],
				specialClass: 'object-cover object-top',
			},
			{
				id: 4,
				imgpre: '/graphic/manuale.jpg',
				image: '/graphic/manuale.png',
				images: [{ type: 'image', src: '/graphic/manuale.png' }],
				title: 'Manuale identità visiva',
				subtitle: 'Graphic Design 2',
				paragraph1:
					"Progetto di rebranding per un'istituzione culturale, con focus sulla rielaborazione dell'identità visiva.",
				paragraph2: "Il caso studio selezionato è stato l'Orto Botanico di Catania.",
				tags: ['Photoshop', 'Illustrator', 'InDesign'],
				specialClass: 'object-cover object-top',
			},
			{
				id: 5,
				imagpre: '/graphic/monogramma.jpg',
				image: '/graphic/monogramma.svg',
				images: [{ type: 'image', src: '/graphic/monogramma.svg' }],
				title: 'Monogramma personale',
				subtitle: 'Graphic Design',
				paragraph1: 'Sviluppo di un monogramma personale.',
				paragraph2: 'Dopo aver esplorato 400 soluzioni grafiche, è stato selezionato il monogramma più efficace.',
				tags: ['Illustrator'],
				specialClass: 'object-cover object-top',
			},
			{
				id: 6,
				imgpre: '/graphic/Guida_Lol.jpg',
				image: '/dev/Guida_LolJ.jpg',
				images: [
					{ type: 'image', src: '/dev/Guida_LolJ.jpg' },
					{ type: 'image', src: '/dev/ezlol/ezLol1.jpg' },
					{ type: 'image', src: '/dev/ezlol/ezLol2.jpg' },
					{ type: 'image', src: '/dev/ezlol/ezLol3.jpg' },
					{ type: 'image', src: '/dev/ezlol/ezLol4.jpg' },
					{ type: 'image', src: '/dev/ezlol/ezLol5.jpg' },
					{ type: 'image', src: '/dev/ezlol/ezLol6.jpg' },
					{ type: 'image', src: '/dev/ezlol/ezLol7.jpg' },
					{ type: 'image', src: '/dev/ezlol/ezLol8.jpg' },
					{ type: 'image', src: '/dev/ezlol/ezLol9.jpg' },
				],
				title: 'Ez+ LoL',
				subtitle: 'Web Design',
				paragraph1: 'Progettazione e sviluppo end-to-end di un sito web.',
				paragraph2:
					"Realizzato completamente in autonomia: dall'UI/UX design all'implementazione con HTML5, CSS3 e JavaScript vanilla.",
				tags: ['HTML5', 'CSS3', 'JavaScript', `jQuery`],
				specialClass: ' object-top',
			},
			{
				id: 7,
				imgpre: '/graphic/Guida_Lol_Redone.jpg',
				image: '/dev/ezlol2/ezLol2.jpg',
				images: [
					{ type: 'image', src: '/dev/ezlol2/ezLol2.jpg' },
					{ type: 'image', src: '/dev/ezlol2/ezLol22.jpg' },
					{ type: 'image', src: '/dev/ezlol2/ezLol23.jpg' },
					{ type: 'image', src: '/dev/ezlol2/ezLol24.jpg' },
					{ type: 'image', src: '/dev/ezlol2/ezLol25.jpg' },
					{ type: 'image', src: '/dev/ezlol2/ezLol26.jpg' },
					{ type: 'image', src: '/dev/ezlol2/ezLol27.jpg' },
					{ type: 'image', src: '/dev/ezlol2/ezLol28.jpg' },
					{ type: 'image', src: '/dev/ezlol2/ezLol29.jpg' },
					{ type: 'image', src: '/dev/ezlol2/ezLol210.jpg' },
				],
				title: 'Ez+ LoL',
				subtitle: 'Rifacimento con stack moderno',
				paragraph1: 'Rearchitettura completa del frontend con tecnologie performanti',
				paragraph2: 'Rewrite completo con stack moderno: Vue 3, Vite e Tailwind per lo styling efficiente.',
				tags: ['Vue 3', 'Vite', 'Tailwind CSS'],
				specialClass: ' object-top',
			},
			{
				id: 8,
				imgpre: '/graphic/calendario.jpg',
				image: '/graphic/calendarioR.jpg',
				images: [
					{ type: 'image', src: '/graphic/calendarioR.jpg' },
					{ type: 'image', src: '/graphic/cal/1Copertinadispersione.jpg' },
					{ type: 'image', src: '/graphic/cal/1Gennaiodoppiaesposizione.jpg' },
					{ type: 'image', src: '/graphic/cal/2Marzotesto.jpg' },
					{ type: 'image', src: '/graphic/cal/3Marzofotoantica.jpg' },
					{ type: 'image', src: '/graphic/cal/4Aprile1polaroid.jpg' },
					{ type: 'image', src: '/graphic/cal/5Maggio.jpg' },
					{ type: 'image', src: '/graphic/cal/6GiugnoAcquerello.jpg' },
					{ type: 'image', src: '/graphic/cal/7Luglio.jpg' },
					{ type: 'image', src: '/graphic/cal/8Agosto1.jpg' },
					{ type: 'image', src: '/graphic/cal/9Settembrevintage.jpg' },
					{ type: 'image', src: '/graphic/cal/10Ottobreoutofbound.jpg' },
					{ type: 'image', src: '/graphic/cal/11Novembre.jpg' },
					{ type: 'image', src: '/graphic/cal/12Dicembreeffettonotte.jpg' },
					// { type: 'pdf', src: 'brochure.pdf' },
					// { type: 'image', src: 'img2.jpg' },
				],
				title: 'Calendario 2023',
				subtitle: 'Computer Graphic',
				paragraph1: 'Calendario realizzato come progetto dimostrativo delle tecniche apprese durante le lezioni',
				paragraph2:
					'Il tema scelto è stato quello della serieTV "The Walking Dead", ma con il calendario da tavolo si basa sul fumetto.',
				tags: ['Photoshop'],
				specialClass: 'object-contain object-center',
			},
			{
				id: 9,
				imgpre: '/graphic/manifesto.jpg',
				image: '/graphic/manifesto.png',
				images: [{ type: 'image', src: '/graphic/manifesto.png' }],
				title: 'Manifesto',
				subtitle: 'Kung Fu - Sanda',
				paragraph1: 'Manifesto realizzato per pubblicizzare il corso di Kung Fu e Sanda',
				paragraph2: ``,
				tags: ['Illustrator', 'InDesign'],
				specialClass: 'object-contain object-top',
			},
			/*{
				id: 9,
				image: '/zapp.png',
				title: 'Vari',
				subtitle: 'Computer Vision',
				paragraph1: 'Vari progetti realizzati per dimostrare le tecniche apprese durante le lezioni',
				paragraph2:
					'I progetti sono stati realizzati applicando tecniche di> Fotogrammetria, 3D, After Effects con Motion Tracking, e utilizzare Google Earth per generare un percorso',
				tags: ['Vue 3', 'Vite', 'Tailwind CSS'],
				specialClass: 'object-contain',
			},*/
			// Aggiungi altri progetti qui
			{
				id: 10,
				imgpre: '/graphic/zapp.jpg',
				image: '/graphic/zapp.png',
				images: [{ type: 'image', src: '/graphic/zapp.png' }],
				title: 'Vari',
				subtitle: 'Computer Vision',
				paragraph1: 'Vari progetti realizzati per dimostrare le tecniche apprese durante le lezioni',
				paragraph2:
					'I progetti sono stati realizzati applicando tecniche di Fotogrammetria, 3D, After Effects con Motion Tracking, e utilizzare Google Earth per generare un percorso',
				tags: ['3D', 'Google Earth Studio', 'After Effects', `AR`, `3DF Zephyr`],
				specialClass: 'object-contain object-center',
			},
			// Aggiungi altri progetti qui
			{
				id: 11,
				imgpre: '/graphic/faririfatti.jpg',
				image: '/graphic/faririfattiJ.jpg',
				images: [{ type: 'image', src: '/graphic/faririfattiJ.jpg' }],
				title: 'Image stitching',
				subtitle: 'Just for fun',
				paragraph1: 'Image stitching basato su un mood horror',
				paragraph2: `Come fonte d'ispirazione è stata scelta la saga di Venerdì 13.`,
				tags: ['Photoshop'],
				specialClass: 'object-cover object-top',
			},
			{
				id: 12,
				imgpre: '/graphic/halloweenDraw.jpg',
				image: '/graphic/halloweenDraw.png',
				images: [{ type: 'image', src: '/graphic/halloweenDraw.png' }],
				title: 'Disegno vettoriale',
				subtitle: 'Just for fun',
				paragraph1: 'Disegno basato su una scena del film Halloween del 1978',
				paragraph2: ``,
				tags: ['Illustrator'],
				specialClass: 'object-contain object-center',
			},
			{
				id: 13,
				imgpre: '/graphic/halloween.jpg',
				image: '/graphic/halloween1.jpg',
				images: [{ type: 'image', src: '/graphic/halloween1.jpg' }],
				title: 'Lavoro misto',
				subtitle: 'Just for fun',
				paragraph1: 'Disegno basato su una scena del film Halloween del 1978',
				paragraph2: ``,
				tags: ['Illustrator'],
				specialClass: 'object-contain object-center',
			},

			{
				id: 14,
				imgpre: '/graphic/Halloween-13th2pre.jpg',
				image: '/graphic/Halloween-13th2.jpg',
				images: [{ type: 'image', src: '/graphic/Halloween-13th2.jpg' }],
				title: 'Image stitching',
				subtitle: 'Just for fun',
				paragraph1: 'Image stitching basato su un mood horror',
				paragraph2: `Come fonte d'ispirazione è stata scelta la saga di Venerdì 13.`,
				tags: ['Photoshop'],
				specialClass: 'object-contain object-top',
			},
		],
	}),
	getters: {
		getProjectById: (state) => (id) => {
			return state.projects.find((project) => project.id === id);
		},
	},
});
