import { defineStore } from 'pinia';


export const useMiniatureStoreDev = defineStore('miniProjects', {
	state: () => ({
projects: [
            {
                id: 30,
                imgpre: '/mini/pre/Scavenger-Seeker.jpg',
                image: '/mini/Scavenger-Seeker.jpg',
                images: [{ type: 'image', src: '/mini/Scavenger-Seeker.jpg' }],
                title: 'Scavenger Seeker',
                subtitle: 'StationForge',
                tags: ['Warhammer40K', 'StationForge', 'Sci-Fi'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 29,
                imgpre: '/mini/pre/Prime-Leader-Of-The-Dragon-Knights.jpg',
                image: '/mini/Prime-Leader-Of-The-Dragon-Knights.jpg',
                images: [{ type: 'image', src: '/mini/Prime-Leader-Of-The-Dragon-Knights.jpg' }],
                title: 'Prime Leader of the Dragon Knights',
                subtitle: 'StationForge',
                tags: ['Warhammer40K',  'StationForge', 'Sci-Fi'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 28,
                imgpre: '/mini/pre/Red-Juggernaut.jpg',
                image: '/mini/Red-Juggernaut.jpg',
                images: [{ type: 'image', src: '/mini/Red-Juggernaut.jpg' }],
                title: 'Red Juggernaut',
                subtitle: 'Warhammer40K',
                tags: ['Warhammer40K',  'Big', 'Sci-Fi'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 27,
                imgpre: '/mini/pre/SPACECRAFT-IMPERIALE.jpg',
                image: '/mini/SPACECRAFT-IMPERIALE.jpg',
                images: [{ type: 'image', src: '/mini/SPACECRAFT-IMPERIALE.jpg' }],
                title: 'Spacecraft Imperiale',
                subtitle: 'Warhammer40K',
                tags: ['Warhammer40K',  'Sci-Fi'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 26,
                imgpre: '/mini/pre/SPACE-MARINE-CON-SCUDO.jpg',
                image: '/mini/SPACE-MARINE-CON-SCUDO.jpg',
                images: [{ type: 'image', src: '/mini/SPACE-MARINE-CON-SCUDO.jpg' }],
                title: 'Space Marine con Scudo',
                subtitle: 'Warhammer40K',
                tags: ['Warhammer40K',  'Sci-Fi'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 25,
                imgpre: '/mini/pre/Solid-snake.jpg',
                image: '/mini/Solid-snake.jpg',
                images: [{ type: 'image', src: '/mini/Solid-snake.jpg' }],
                title: 'Solid Snake',
                subtitle: 'Metal Gear Solid',
                tags: ['Metal Gear',  'Stealth'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 24,
                imgpre: '/mini/pre/Terminator.jpg',
                image: '/mini/Terminator.jpg',
                images: [{ type: 'image', src: '/mini/Terminator.jpg' }],
                title: 'Terminator',
                subtitle: 'Warhammer40K',
                tags: ['Warhammer40K',  'Sci-Fi', 'Terminator', 'Terminator'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 23,
                imgpre: '/mini/pre/John-Wick.jpg',
                image: '/mini/John-Wick.jpg',
                images: [{ type: 'image', src: '/mini/John-Wick.jpg' }],
                title: 'John Wick',
                subtitle: 'John Wick',
                tags: ['Movie', 'Action'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 22,
                imgpre: '/mini/pre/Alex-Mercer2.jpg',
                image: '/mini/Alex-Mercer2.jpg',
                images: [{ type: 'image', src: '/mini/Alex-Mercer2.jpg' }],
                title: 'Alex Mercer',
                subtitle: 'Prototype',
                tags: ['Prototype', 'Action', 'Virus'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 21,
                imgpre: '/mini/pre/Lord-Discordant-on-Helstalker.jpg',
                image: '/mini/Lord-Discordant-on-Helstalker.jpg',
                images: [{ type: 'image', src: '/mini/Lord-Discordant-on-Helstalker.jpg' }],
                title: 'Lord Discordant on Helstalker',
                subtitle: 'Warhammer40K',
                tags: ['Warhammer40K', 'Chaos Space Marines', 'Sci-Fi'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 20,
                imgpre: '/mini/pre/Soraka.jpg',
                image: '/mini/Soraka.jpg',
                images: [{ type: 'image', src: '/mini/Soraka.jpg' }],
                title: 'Soraka',
                subtitle: 'League of Legends',
                tags: ['League of Legends', 'Fantasy'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 19,
                imgpre: '/mini/pre/SkullTaker.jpg',
                image: '/mini/SkullTaker.jpg',
                images: [{ type: 'image', src: '/mini/SkullTaker.jpg' }],
                title: 'SkullTaker',
                subtitle: 'Warhammer Fantasy',
                tags: ['Warhammer Fantasy', 'Fantasy', 'Khorne', 'Chaos'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 18,
                imgpre: '/mini/pre/Frozen.jpg',
                image: '/mini/Frozen.jpg',
                images: [{ type: 'image', src: '/mini/Frozen.jpg' }],
                title: 'Elsa',
                subtitle: 'Frozen',
                tags: ['Disney', 'Animation', 'Frozen', 'Kid'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 17,
                imgpre: '/mini/pre/Kuma.jpg',
                image: '/mini/Kuma.jpg',
                images: [{ type: 'image', src: '/mini/Kuma.jpg' }],
                title: 'Kuma',
                subtitle: 'One Piece',
                tags: ['One Piece', 'Manga', 'Anime' ],
                specialClass: 'object-contain object-top',
            },

            // --- NUOVI CHE MANCAVANO ---

            {
                id: 16,
                imgpre: '/mini/pre/Skink-Oracle-on-Trogledon.jpg',
                image: '/mini/Skink-Oracle-on-Trogledon.jpg',
                images: [{ type: 'image', src: '/mini/Skink-Oracle-on-Trogledon.jpg' }],
                title: 'Skink Oracle on Trogledon',
                subtitle: 'Warhammer Fantasy',
                tags: ['Warhammer Fantasy', 'Fantasy', 'Seraphon', 'Big', 'Mounted'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 15,
                imgpre: '/mini/pre/Apothecary.jpg',
                image: '/mini/Apothecary.jpg',
                images: [{ type: 'image', src: '/mini/Apothecary.jpg' }],
                title: 'APOTHECARY BIOLOGIS Primaris',
                subtitle: 'Warhammer40K',
                tags: ['Warhammer40K', 'Sci-Fi', 'Medical', 'Space Marine'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 14,
                imgpre: '/mini/pre/Connor.jpg',
                image: '/mini/Connor.jpg',
                images: [{ type: 'image', src: '/mini/Connor.jpg' }],
                title: 'Connor',
                subtitle: 'Assassin’s Creed 3',
                tags: ['Assassin’s Creed', 'Action'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 13,
                imgpre: '/mini/pre/Lord-Commander-Bastian-Carthalos.jpg',
                image: '/mini/Lord-Commander-Bastian-Carthalos.jpg',
                images: [{ type: 'image', src: '/mini/Lord-Commander-Bastian-Carthalos.jpg' }],
                title: 'Lord Commander Bastian Carthalos',
                subtitle: 'Warhammer Fantasy',
                tags: ['Warhammer Fantasy', 'Fantasy', 'Stormcast Eternals', 'Sigmar'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 12,
                imgpre: '/mini/pre/Skyborne-marine.jpg',
                image: '/mini/Skyborne-marine.jpg',
                images: [{ type: 'image', src: '/mini/Skyborne-marine.jpg' }],
                title: 'Skyborne Marine',
                subtitle: 'Warhammer40K',
                tags: ['Warhammer40K', 'Sci-Fi', 'Space Marine', 'Skyborne', 'Custodes'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 11,
                imgpre: '/mini/pre/Imotekh.jpg',
                image: '/mini/Imotekh.jpg',
                images: [{ type: 'image', src: '/mini/Imotekh.jpg' }],
                title: 'Imotekh',
                subtitle: 'Warhammer40K',
                tags: ['Warhammer40K', 'Sci-Fi', 'Necrons', 'Imotekh', 'Phaeron'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 10,
                imgpre: '/mini/pre/Space-marine.jpg',
                image: '/mini/Space-marine.jpg',
                images: [{ type: 'image', src: '/mini/Space-marine.jpg' }],
                title: 'Space Marine',
                subtitle: 'Warhammer40K',
                tags: ['Warhammer40K', 'Sci-Fi', 'Space Marine'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 9,
                imgpre: '/mini/pre/Terminator-Captain.jpg',
                image: '/mini/Terminator-Captain.jpg',
                images: [{ type: 'image', src: '/mini/Terminator-Captain.jpg' }],
                title: 'Terminator Captain',
                subtitle: 'Warhammer40K',
                tags: ['Warhammer40K', 'Sci-Fi', 'Space Marine', 'Terminator', 'Captain'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 8,
                imgpre: '/mini/pre/Space-marine-d-assalto.jpg',
                image: '/mini/Space-marine-d-assalto.jpg',
                images: [{ type: 'image', src: '/mini/Space-marine-d-assalto.jpg' }],
                title: "Space Marine d'Assalto",
                subtitle: 'Warhammer40K',
                tags: ['Warhammer40K', 'Sci-Fi', 'Space Marine', 'Sword'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 7,
                imgpre: '/mini/pre/Custom-Titus.jpg',
                image: '/mini/Custom-Titus.jpg',
                images: [{ type: 'image', src: '/mini/Custom-Titus.jpg' }],
                title: 'Custom Titus',
                subtitle: 'Warhammer40K',
                tags: ['Warhammer40K', 'Sci-Fi', 'Space Marine', 'Titus'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 6,
                imgpre: '/mini/pre/Ranger-Tattico.jpg',
                image: '/mini/Ranger-Tattico.jpg',
                images: [{ type: 'image', src: '/mini/Ranger-Tattico.jpg' }],
                title: 'Ranger Tattico',
                subtitle: 'Warhammer40K',
                tags: ['Warhammer40K', 'Sci-Fi', 'Space Marine', 'Ranger'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 5,
                imgpre: '/mini/pre/Marine-con-Magnoculars.jpg',
                image: '/mini/Marine-con-Magnoculars.jpg',
                images: [{ type: 'image', src: '/mini/Marine-con-Magnoculars.jpg' }],
                title: 'Marine con Mangnoculars',
                subtitle: 'Warhammer40K',
                tags: ['Warhammer40K', 'Sci-Fi', 'Space Marine', 'Magnoculars'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 4,
                imgpre: '/mini/pre/Capitano-dei-Blood-Angels.jpg',
                image: '/mini/Capitano-dei-Blood-Angels.jpg',
                images: [{ type: 'image', src: '/mini/Capitano-dei-Blood-Angels.jpg' }],
                title: 'Capitano dei Blood Angels',
                subtitle: 'Warhammer40K',
                tags: ['Warhammer40K', 'Sci-Fi', 'Space Marine', 'Blood Angels', 'Captain'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 3,
                imgpre: '/mini/pre/SPACE-MARINE-D’ELITE.jpg',
                image: '/mini/SPACE-MARINE-D’ELITE.jpg',
                images: [{ type: 'image', src: '/mini/SPACE-MARINE-D’ELITE.jpg' }],
                title: 'Space Marine d’Elite',
                subtitle: 'Warhammer40K',
                tags: ['Warhammer40K', 'Sci-Fi', 'Space Marine', 'Elite', 'Sword', 'Bolter'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 2,
                imgpre: '/mini/pre/Tech-Striker-AGRESSOR_TERMINATORCHAMP.jpg',
                image: '/mini/Tech-Striker-AGRESSOR_TERMINATORCHAMP.jpg',
                images: [{ type: 'image', src: '/mini/Tech-Striker-AGRESSOR_TERMINATORCHAMP.jpg' }],
                title: 'Tech Striker Agressor Terminator Champ',
                subtitle: 'Warhammer40K',
                tags: ['Warhammer40K', 'Sci-Fi', 'Space Marine', 'Terminator', 'Techmarine'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 1,
                imgpre: '/mini/pre/Sonic.jpg',
                image: '/mini/Sonic.jpg',
                images: [{ type: 'image', src: '/mini/Sonic.jpg' }],
                title: 'Sonic',
                subtitle: 'Sonic the Hedgehog',
                tags: ['Sonic', 'Platformer'],
                specialClass: 'object-contain object-top',
            },
        ],
	}),
	getters: {
		getProjectById: (state) => (id) => {
			return state.projects.find((project) => project.id === id);
		},
	},
});
