import { defineStore } from 'pinia';


export const useMiniatureStoreDev = defineStore('miniProjects', {
	state: () => ({
projects: [
            {
                id: 30,
                imgpre: '/mini/pre/Scavenger-Seeker.jpg',
                image: '/mini/Scavenger-Seeker.jpg',
                images: [{ type: 'image', src: '/mini/Scavenger-Seeker.jpg' }],
                title: 'Scavenger Seeker',
                subtitle: 'Miniature',
                tags: ['Warhammer', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 29,
                imgpre: '/mini/pre/Prime-Leader-Of-The-Dragon-Knights.jpg',
                image: '/mini/Prime-Leader-Of-The-Dragon-Knights.jpg',
                images: [{ type: 'image', src: '/mini/Prime-Leader-Of-The-Dragon-Knights.jpg' }],
                title: 'Prime Leader of the Dragon Knights',
                subtitle: 'Miniature',
                tags: ['Warhammer', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 28,
                imgpre: '/mini/pre/Red-Juggernaut.jpg',
                image: '/mini/Red-Juggernaut.jpg',
                images: [{ type: 'image', src: '/mini/Red-Juggernaut.jpg' }],
                title: 'Red Juggernaut',
                subtitle: 'Miniature',
                tags: ['Warhammer', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 27,
                imgpre: '/mini/pre/SPACECRAFT-IMPERIALE.jpg',
                image: '/mini/SPACECRAFT-IMPERIALE.jpg',
                images: [{ type: 'image', src: '/mini/SPACECRAFT-IMPERIALE.jpg' }],
                title: 'Spacecraft Imperiale',
                subtitle: 'Miniature',
                tags: ['Sci-Fi', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 26,
                imgpre: '/mini/pre/SPACE-MARINE-CON-SCUDO.jpg',
                image: '/mini/SPACE-MARINE-CON-SCUDO.jpg',
                images: [{ type: 'image', src: '/mini/SPACE-MARINE-CON-SCUDO.jpg' }],
                title: 'Space Marine con Scudo',
                subtitle: 'Miniature',
                tags: ['Warhammer', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 25,
                imgpre: '/mini/pre/Solid-snake.jpg',
                image: '/mini/Solid-snake.jpg',
                images: [{ type: 'image', src: '/mini/Solid-snake.jpg' }],
                title: 'Solid Snake',
                subtitle: 'Fan Art Miniature',
                tags: ['Metal Gear', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 24,
                imgpre: '/mini/pre/Terminator.jpg',
                image: '/mini/Terminator.jpg',
                images: [{ type: 'image', src: '/mini/Terminator.jpg' }],
                title: 'Terminator',
                subtitle: 'Fan Art Miniature',
                tags: ['Sci-Fi', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 23,
                imgpre: '/mini/pre/John-Wick.jpg',
                image: '/mini/John-Wick.jpg',
                images: [{ type: 'image', src: '/mini/John-Wick.jpg' }],
                title: 'John Wick',
                subtitle: 'Fan Art Miniature',
                tags: ['Movie', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 22,
                imgpre: '/mini/pre/Alex-Mercer2.jpg',
                image: '/mini/Alex-Mercer2.jpg',
                images: [{ type: 'image', src: '/mini/Alex-Mercer2.jpg' }],
                title: 'Alex Mercer',
                subtitle: 'Fan Art Miniature',
                tags: ['Prototype', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 21,
                imgpre: '/mini/pre/Lord-Discordant-on-Helstalker.jpg',
                image: '/mini/Lord-Discordant-on-Helstalker.jpg',
                images: [{ type: 'image', src: '/mini/Lord-Discordant-on-Helstalker.jpg' }],
                title: 'Lord Discordant on Helstalker',
                subtitle: 'Warhammer',
                tags: ['Warhammer', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 20,
                imgpre: '/mini/pre/Soraka.jpg',
                image: '/mini/Soraka.jpg',
                images: [{ type: 'image', src: '/mini/Soraka.jpg' }],
                title: 'Soraka',
                subtitle: 'Fan Art Miniature',
                tags: ['League of Legends', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 19,
                imgpre: '/mini/pre/SkullTaker.jpg',
                image: '/mini/SkullTaker.jpg',
                images: [{ type: 'image', src: '/mini/SkullTaker.jpg' }],
                title: 'SkullTaker',
                subtitle: 'Miniature',
                tags: ['Fantasy', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 18,
                imgpre: '/mini/pre/Frozen.jpg',
                image: '/mini/Frozen.jpg',
                images: [{ type: 'image', src: '/mini/Frozen.jpg' }],
                title: 'Frozen',
                subtitle: 'Miniature',
                tags: ['Fantasy', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 17,
                imgpre: '/mini/pre/Kuma.jpg',
                image: '/mini/Kuma.jpg',
                images: [{ type: 'image', src: '/mini/Kuma.jpg' }],
                title: 'Kuma',
                subtitle: 'Miniature',
                tags: ['Fantasy', 'Painting'],
                specialClass: 'object-contain object-top',
            },

            // --- NUOVI CHE MANCAVANO ---

            {
                id: 16,
                imgpre: '/mini/pre/Skink-Oracle-on-Trogledon.jpg',
                image: '/mini/Skink-Oracle-on-Trogledon.jpg',
                images: [{ type: 'image', src: '/mini/Skink-Oracle-on-Trogledon.jpg' }],
                title: 'Skink Oracle on Trogledon',
                subtitle: 'Miniature',
                tags: ['Warhammer', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 15,
                imgpre: '/mini/pre/Apothecary.jpg',
                image: '/mini/Apothecary.jpg',
                images: [{ type: 'image', src: '/mini/Apothecary.jpg' }],
                title: 'Apothecary',
                subtitle: 'Miniature',
                tags: ['Warhammer', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 14,
                imgpre: '/mini/pre/Connor.jpg',
                image: '/mini/Connor.jpg',
                images: [{ type: 'image', src: '/mini/Connor.jpg' }],
                title: 'Connor',
                subtitle: 'Miniature',
                tags: ['Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 13,
                imgpre: '/mini/pre/Lord-Commander-Bastian-Carthalos.jpg',
                image: '/mini/Lord-Commander-Bastian-Carthalos.jpg',
                images: [{ type: 'image', src: '/mini/Lord-Commander-Bastian-Carthalos.jpg' }],
                title: 'Lord Commander Bastian Carthalos',
                subtitle: 'Miniature',
                tags: ['Warhammer', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 12,
                imgpre: '/mini/pre/Skyborne-marine.jpg',
                image: '/mini/Skyborne-marine.jpg',
                images: [{ type: 'image', src: '/mini/Skyborne-marine.jpg' }],
                title: 'Skyborne Marine',
                subtitle: 'Miniature',
                tags: ['Warhammer', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 11,
                imgpre: '/mini/pre/Imotekh.jpg',
                image: '/mini/Imotekh.jpg',
                images: [{ type: 'image', src: '/mini/Imotekh.jpg' }],
                title: 'Imotekh',
                subtitle: 'Miniature',
                tags: ['Warhammer', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 10,
                imgpre: '/mini/pre/Space-marine.jpg',
                image: '/mini/Space-marine.jpg',
                images: [{ type: 'image', src: '/mini/Space-marine.jpg' }],
                title: 'Space Marine',
                subtitle: 'Miniature',
                tags: ['Warhammer', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 9,
                imgpre: '/mini/pre/Terminator-Captain.jpg',
                image: '/mini/Terminator-Captain.jpg',
                images: [{ type: 'image', src: '/mini/Terminator-Captain.jpg' }],
                title: 'Terminator Captain',
                subtitle: 'Miniature',
                tags: ['Warhammer', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 8,
                imgpre: '/mini/pre/Space-marine-d-assalto.jpg',
                image: '/mini/Space-marine-d-assalto.jpg',
                images: [{ type: 'image', src: '/mini/Space-marine-d-assalto.jpg' }],
                title: "Space Marine d'Assalto",
                subtitle: 'Miniature',
                tags: ['Warhammer', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 7,
                imgpre: '/mini/pre/Custom-Titus.jpg',
                image: '/mini/Custom-Titus.jpg',
                images: [{ type: 'image', src: '/mini/Custom-Titus.jpg' }],
                title: 'Custom Titus',
                subtitle: 'Miniature',
                tags: ['Warhammer', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 6,
                imgpre: '/mini/pre/Ranger-Tattico.jpg',
                image: '/mini/Ranger-Tattico.jpg',
                images: [{ type: 'image', src: '/mini/Ranger-Tattico.jpg' }],
                title: 'Ranger Tattico',
                subtitle: 'Miniature',
                tags: ['Warhammer', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 5,
                imgpre: '/mini/pre/Marine-con-Magnoculars.jpg',
                image: '/mini/Marine-con-Magnoculars.jpg',
                images: [{ type: 'image', src: '/mini/Marine-con-Magnoculars.jpg' }],
                title: 'Marine con Mangnoculars',
                subtitle: 'Miniature',
                tags: ['Warhammer', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 4,
                imgpre: '/mini/pre/Capitano-dei-Blood-Angels.jpg',
                image: '/mini/Capitano-dei-Blood-Angels.jpg',
                images: [{ type: 'image', src: '/mini/Capitano-dei-Blood-Angels.jpg' }],
                title: 'Capitano dei Blood Angels',
                subtitle: 'Miniature',
                tags: ['Warhammer', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 3,
                imgpre: '/mini/pre/SPACE-MARINE-D’ELITE.jpg',
                image: '/mini/SPACE-MARINE-D’ELITE.jpg',
                images: [{ type: 'image', src: '/mini/SPACE-MARINE-D’ELITE.jpg' }],
                title: 'Space Marine Delle',
                subtitle: 'Miniature',
                tags: ['Warhammer', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 2,
                imgpre: '/mini/pre/Tech-Striker-AGRESSOR_TERMINATORCHAMP.jpg',
                image: '/mini/Tech-Striker-AGRESSOR_TERMINATORCHAMP.jpg',
                images: [{ type: 'image', src: '/mini/Tech-Striker-AGRESSOR_TERMINATORCHAMP.jpg' }],
                title: 'Tech Striker Agressor Terminator Champ',
                subtitle: 'Miniature',
                tags: ['Warhammer', 'Painting'],
                specialClass: 'object-contain object-top',
            },
            {
                id: 1,
                imgpre: '/mini/pre/Sonic.jpg',
                image: '/mini/Sonic.jpg',
                images: [{ type: 'image', src: '/mini/Sonic.jpg' }],
                title: 'Sonic',
                subtitle: 'Fan Art Miniature',
                tags: ['Painting'],
                specialClass: 'object-contain object-top',
            },
        ],
	}),
	getters: {
		getProjectById: (state) => (id) => {
			return state.projects.find((project) => project.id === id);
		},
	},
});
